# Generated by Django 4.1.6 on 2023-02-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameraterapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(through='gameraterapi.GameCategory', to='gameraterapi.category'),
        ),
    ]
